# Site settings
title: Personal blog
email: your-email@domain.com
description: "A personal blog where I will publish projects or anything important to me."
baseurl: ""
url: "http://leosnchez16.com"

# Build settings
markdown: kramdown
permalink: /:title
comments: true
